# Hydra Service Accounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hydra-auth
  namespace: hydra-system
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/component: auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-pod-controller
  namespace: hydra-system
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-workload
  namespace: hydra-students
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/component: student
