apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: hydra-infra
type: Opaque
stringData:
  postgres-user: "n8n"
  postgres-password: "Metathesiophobia"
  postgres-db: "n8n"
  n8n-encryption-key: "YezdeYezdegerdiangerdian"
  n8n-user-manager-api-key: "f9653bd43d184a02a059e4eee866b31f"
