apiVersion: v1
kind: Service
metadata:
  name: sshpiper
  namespace: hydra-infra
  labels:
    app: sshpiper
spec:
  type: NodePort
  selector:
    app: sshpiper
  ports:
    - port: 2222
      targetPort: 2222
      nodePort: 32222
      name: ssh
